<?php
$z[0]=Array("link"," http://www.dedecms.com/upimg/soft/2009/DedecmsV55-GBK-Final.tar.gz ",0,121);
$z[0][4]['text']="V55-GBK版安装程序";
$z[1]=Array("link"," http://www.dedecms.com/upimg/soft/2009/DedecmsV55-UTF8-Final.tar.gz ",122,245);
$z[1][4]['text']="V55-UTF8版安装程序";
$z[2]=Array("link"," http://updatenew.dedecms.com/downloads/v53gbk-upv55.zip ",246,362);
$z[2][4]['text']="V5.3.1到V5.5GBK升级程序";
$z[3]=Array("link"," http://updatenew.dedecms.com/downloads/v53utf8-upv55.zip ",363,481);
$z[3][4]['text']="V5.3.1到V5.5UTF8升级程序";
$z[4]=Array("link"," http://www.dedecms.com/hdwiki/downloads/Dedecms55&HDwiki4.05_GBK-Final_0916.tar.gz ",482,655);
$z[4][4]['text']="DedeCMS V5.5GBK + HDwiki V4.05 互动百科整合安装包";
$z[5]=Array("link"," http://www.dedecms.com/hdwiki/downloads/Dedecms55&HDwiki4.05_UTF8-Final_0916.tar.gz ",656,831);
$z[5][4]['text']="DedeCMS V5.5UTF8 + HDwiki V4.05 互动百科整合安装包";

?>