<?php
$z[0]=Array("pubdate","",10,56);
$z[0][4]['function']="GetDateTimeMK(@me)";
$z[1]=Array("typelink","",64,131);
$z[1][4]['function']="str_replace(\"a \",\"a class=ulink \",@me)";
$z[2]=Array("arcurl","",154,169);
$z[3]=Array("title","",187,201);
$z[4]=Array("click","",213,227);
$z[5]=Array("arcurl","",264,279);
$z[6]=Array("title","",302,316);
$z[7]=Array("litpic","",318,368);
$z[7][4]['function']="CkLitImageView(@me,120)";
$z[8]=Array("description","",373,393);
$z[9]=Array("arcurl","",417,432);

?>