<?php
$z[0]=Array("pagestyle"," @me= (@me==3 ? '<li>' : '');",17,94);
$z[0][4]['runphp']="yes";
$z[1]=Array("linkurl","",120,136);
$z[2]=Array("pagestyle"," @me= (@me==3 ? 'class=\"pic\"' : ''); ",138,223);
$z[2][4]['runphp']="yes";
$z[3]=Array("imgsrc","",253,268);
$z[4]=Array("imgwidth","",282,300);
$z[5]=Array("alttext","",306,323);
$z[6]=Array("linkurl","",385,401);
$z[7]=Array("pagestyle","@me = (@me==3 ? 'class=\"title\"' : '');",403,489);
$z[7][4]['runphp']="yes";
$z[8]=Array("title","",508,523);
$z[9]=Array("pagestyle"," @me = (@me==3 ? '</li>' : ''); ",561,641);
$z[9][4]['runphp']="yes";

?>