<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",15,169);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",184,199);
$z[2]=Array("title","",215,229);
$z[3]=Array("pubdate","",295,341);
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("softrank","",378,423);
$z[4][4]['function']="GetRankStar(@me)";
$z[5]=Array("language","",460,477);
$z[6]=Array("click","",514,528);
$z[7]=Array("description","",571,591);

?>