<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50111.jpg ",92,309);
$z[1][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50111.jpg";
$z[1][4]['text']="海岛风光";
$z[1][4]['width']="670";
$z[1][4]['height']="502";
$z[2]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50112.jpg ",310,527);
$z[2][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50112.jpg";
$z[2][4]['text']="海岛风光";
$z[2][4]['width']="670";
$z[2][4]['height']="502";
$z[3]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50113.jpg ",528,745);
$z[3][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50113.jpg";
$z[3][4]['text']="海岛风光";
$z[3][4]['width']="670";
$z[3][4]['height']="502";
$z[4]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50114.jpg ",746,963);
$z[4][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50114.jpg";
$z[4][4]['text']="海岛风光";
$z[4][4]['width']="670";
$z[4][4]['height']="502";
$z[5]=Array("img"," http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50115.jpg ",964,1181);
$z[5][4]['ddimg']="http://www.dedecms.com/demoimg/uploads/allimg/100407/1-10040G50115.jpg";
$z[5][4]['text']="海岛风光";
$z[5][4]['width']="670";
$z[5][4]['height']="448";

?>