<?php
$z[0]=Array("spaceurl","",87,105);
$z[1]=Array("face","",134,147);
$z[2]=Array("spaceurl","",193,211);
$z[3]=Array("uname","",230,244);
$z[4]=Array("spaceurl","",292,310);
$z[5]=Array("spaceurl","",387,405);
$z[6]=Array("spaceurl","",475,493);
$z[7]=Array("rankname","",620,638);
$z[8]=Array("jointime","",705,757);
$z[8][4]['function']="MyDate('Y-m-d H:m',@me)";
$z[9]=Array("logintime","",824,877);
$z[9][4]['function']="MyDate('Y-m-d H:m',@me)";

?>