<?php
$z[0]=Array("type","\r\n	  <div class=\"channel_tit\">\r\n	      <div class=\"l\"><h4><a href=\"[field:typelink /]\" target=\"_blank\">[field:typename /]</a></h4></div>\r\n		  <div class=\"r\"><span><a href=\"[field:typelink /]\" target=\"_blank\"><img src=\"/templets/img_v4/more.gif\" alt=\"更多\" /></a></span></div>\r\n	  </div>\r\n	  ",33,349);
$z[1]=Array("arclist","\r\n		<div class=\"p\">[field:imglink /]</div>\r\n		<div class=\"t\"><a href=\"[field:filename/]\" target=\"_blank\">[field:title/]</a><p>[field:info/]</p></div>\r\n		",386,679);
$z[1][4]['type']="commend";
$z[1][4]['typeid']="0";
$z[1][4]['row']="1";
$z[1][4]['att']="0";
$z[1][4]['imgwidth']="52";
$z[1][4]['imgheight']="40";
$z[1][4]['titlelen']="20";
$z[1][4]['infolen']="30";
$z[2]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n			  ",750,916);
$z[2][4]['row']="10";
$z[2][4]['att']="0";
$z[2][4]['titlelen']="40";
$z[2][4]['orderby']="ID";

?>