<?php
$z[0]=Array("link"," http://www.dedecms.com/upimg/soft/2008/dedecmsv51-gbk.zip ",0,122);
$z[0][4]['text']="DedeCms V5.1 GBK 全新安装包";
$z[1]=Array("link"," http://www.dedecms.com/upimg/soft/2008/dedecmsv51-utf8.zip ",123,248);
$z[1][4]['text']="DedeCms V5.1 UTF-8 全新安装包";
$z[2]=Array("link"," http://pw.dedecms.com/dedecmsv51sp1.zip ",249,356);
$z[2][4]['text']="DedeCms V5.1SP1 GBK 全新安装包";
$z[3]=Array("link"," http://pw.dedecms.com/dedecmsv51sp1utf8.zip ",357,470);
$z[3][4]['text']="DedeCms V5.1SP1 UTF-8 全新安装包";
$z[4]=Array("link"," http://www.dedecms.com/upimg/soft/2008/dedecmsv51-v4up.zip ",471,596);
$z[4][4]['text']="DedeCms V4.0 to 5.1GBK升级程序";
$z[5]=Array("link"," http://www.dedecms.com/upimg/soft/2008/dedecmsv51-501up.zip ",597,729);
$z[5][4]['text']="DedeCms V5.01 GBK to 5.1 GBK升级程序";
$z[6]=Array("link"," http://www.dedecms.com/upimg/soft/2008/dedecmsv51-501up-utf8.zip ",730,871);
$z[6][4]['text']="DedeCms V5.01 UTF-8 to 5.1 UTF-8升级程序";

?>