{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/131009/1-1310091AA9.jpg' text='图标' width='206' height='104'} /uploads/allimg/131009/1-1310091AA9.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/131009/1-1310091AH5.jpg' text='荷塘' width='800' height='600'} /uploads/allimg/131009/1-1310091AH5.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/131009/1-1310091AH6.jpg' text='雾凇' width='800' height='600'} /uploads/allimg/131009/1-1310091AH6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/131009/1-1310091AH6-50.jpg' text='标识' width='200' height='97'} /uploads/allimg/131009/1-1310091AH6-50.jpg {/dede:img}
