<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/131009/1-1310091AA9.jpg ",93,242);
$z[1][4]['ddimg']="/uploads/allimg/131009/1-1310091AA9.jpg";
$z[1][4]['text']="图标";
$z[1][4]['width']="206";
$z[1][4]['height']="104";
$z[2]=Array("img"," /uploads/allimg/131009/1-1310091AH5.jpg ",244,393);
$z[2][4]['ddimg']="/uploads/allimg/131009/1-1310091AH5.jpg";
$z[2][4]['text']="荷塘";
$z[2][4]['width']="800";
$z[2][4]['height']="600";
$z[3]=Array("img"," /uploads/allimg/131009/1-1310091AH6.jpg ",395,544);
$z[3][4]['ddimg']="/uploads/allimg/131009/1-1310091AH6.jpg";
$z[3][4]['text']="雾凇";
$z[3][4]['width']="800";
$z[3][4]['height']="600";
$z[4]=Array("img"," /uploads/allimg/131009/1-1310091AH6-50.jpg ",546,700);
$z[4][4]['ddimg']="/uploads/allimg/131009/1-1310091AH6-50.jpg";
$z[4][4]['text']="标识";
$z[4][4]['width']="200";
$z[4][4]['height']="97";

?>