<?php
$z[0]=Array("global","",152,177);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",243,268);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",330,355);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",388,414);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",542,569);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",642,669);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",672,698);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",857,884);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",896,928);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",975,1001);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1056,1091);
$z[10][4]['name']="innerTopBanner1";
$z[11]=Array("myad","",1126,1161);
$z[11][4]['name']="innerTopBanner2";
$z[12]=Array("global","",1464,1489);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1529,1772);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",1864,1889);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2697,2827);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>