<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-10-01 21:28:26
*/
?>
<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-10-01 23:14:00
*/
?>
<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-10-01 23:14:01
*/
?>
<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-10-01 23:14:01
*/
?>
<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-10-01 23:14:02
*/
?>
